[package]

name = "piston-example-sprite"
version = "0.0.1"
authors = ["Coeuvre Wong <coeuvre@gmail.com>"]

[[bin]]

name = "piston-example-sprite"

[dependencies.sprite]

git = "https://github.com/pistondevelopers/sprite"

[dependencies.sdl2_window]

git = "https://github.com/pistondevelopers/sdl2_window"

[dependencies.opengl_graphics]

git = "https://github.com/pistondevelopers/opengl_graphics"

