[package]
name = "piston-examples"
version = "0.0.0"
edition = "2024"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = []

[dependencies.piston_window]
version = "0.139.0"
features = ["batteries"]

