[package]
name = "piston-examples"
version = "0.0.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = []

[[bin]]
name = "hello_world"
path = "src/hello_world.rs"

[[bin]]
name = "draw_state"
path = "src/draw_state.rs"

[[bin]]
name = "sprite"
path = "src/sprite.rs"

[[bin]]
name = "image"
path = "src/image.rs"

[[bin]]
name = "paint"
path = "src/paint.rs"

[[bin]]
name = "deform"
path = "src/deform.rs"

[[bin]]
name = "cube"
path = "src/cube.rs"

[[bin]]
name = "texture_swap"
path = "src/texture_swap.rs"

[[bin]]
name = "multi_window"
path = "src/multi_window.rs"

[dependencies]
piston_window = "0.55.0"
find_folder = "0.3.0"
piston-ai_behavior = "0.16.0"
piston2d-sprite = "0.28.0"
image = "0.10.0"
piston2d-drag_controller = "0.15.0"
gfx = "0.12.0"
gfx_device_gl = "0.11.0"
vecmath = "0.2.0"
camera_controllers = "0.17.0"
pistoncore-sdl2_window = "0.36.0"
rand = "0.3.14"
shader_version = "0.2.1"
