[package]
name = "piston-example-user_input"
version = "0.0.0"
authors = ["Your Name <your@email.com>"]
keywords = []

[[bin]]
name = "piston-example-user_input"
path = "src/main.rs"

[dependencies]
piston = "0.2.0"
piston2d-opengl_graphics = "0.1.0"
piston2d-graphics = "0.1.4"

[dependencies.pistoncore-sdl2_window]
version = "0.1.0"
optional = true

[dependencies.pistoncore-glfw_window]
version = "0.1.0"
optional = true

[dependencies.pistoncore-glutin_window]
version = "0.2.1"
optional = true

[features]
default = ["include_glutin"]
include_sdl2 = ["pistoncore-sdl2_window"]
include_glfw = ["pistoncore-glfw_window"]
include_glutin = ["pistoncore-glutin_window"]
