[package]

name = "cube"
version = "0.0.0"
authors = ["Your Name <your@email.com>"]
tags = []

[[bin]]

name = "cube"
path = "src/main.rs"

[dependencies.cam]

git = "https://github.com/PistonDevelopers/cam"

[dependencies.glfw_game_window]

git = "https://github.com/pistondevelopers/glfw_game_window"

[dependencies.sdl2_game_window]

git = "https://github.com/pistondevelopers/sdl2_game_window"

[dependencies.gfx]

git = "https://github.com/gfx-rs/gfx-rs"

