[package]
name = "cube"
version = "0.0.0"
authors = ["Your Name <your@email.com>"]
tags = []

[[bin]]
name = "cube"
path = "src/main.rs"

[dependencies.pistoncore-event]
git = "https://github.com/PistonDevelopers/event"

[dependencies.pistoncore-sdl2_window]
git = "https://github.com/pistondevelopers/sdl2_window"

[dependencies.piston3d-cam]
git = "https://github.com/PistonDevelopers/cam"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"
